
<!DOCTYPE html>
<html lang="en-US">
<link href="img/favicon.ico" rel="icon">
    <!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"> 
    <!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <!-- Libraries Stylesheet -->
<link href="{{asset('home/lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
<link rel='stylesheet' id='contact-form-7-css' href='https://eforma.fr/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.8' media='all' />
<link rel='stylesheet' id='faq-schema-ultimate-css' href='https://eforma.fr/wp-content/plugins/faq-schema-ultimate/public/css/faq-schema-ultimate-public.css?ver=1.0.0' media='all' />
<link rel='stylesheet' id='toc-screen-css' href='https://eforma.fr/wp-content/plugins/table-of-contents-plus/screen.min.css?ver=2302' media='all' />
<link rel='stylesheet' id='megamenu-css' href='https://eforma.fr/wp-content/uploads/maxmegamenu/style.css?ver=69f062' media='all' />
<link rel='stylesheet' id='dashicons-css' href='https://eforma.fr/wp-includes/css/dashicons.min.css?ver=6.3' media='all' />
<link rel='stylesheet' id='style-css' href='https://eforma.fr/wp-content/themes/eforma/style.css?ver=3.0.3' media='all' />
<link rel='stylesheet' id='main-css' href='https://eforma.fr/wp-content/themes/eforma/assets/css/main.css?ver=3.0.3' media='all' />
<link rel='stylesheet' id='jost-css' href='//fonts.googleapis.com/css?family=Jost%3A100%2C200%2C300%2Cregular%2C500%2C600%2C700%2C800%2C900%2C100italic%2C200italic%2C300italic%2Citalic%2C500italic%2C600italic%2C700italic%2C800italic%2C900italic&#038;subset=cyrillic%2Clatin%2Clatin-ext&#038;ver=2.9.6' media='all' />
<link rel='stylesheet' id='kc-general-css' href='https://eforma.fr/wp-content/plugins/kingcomposer/assets/frontend/css/kingcomposer.min.css?ver=2.9.6' media='all' />
<link rel='stylesheet' id='kc-animate-css' href='https://eforma.fr/wp-content/plugins/kingcomposer/assets/css/animate.css?ver=2.9.6' media='all' />
<link rel='stylesheet' id='kc-icon-1-css' href='https://eforma.fr/wp-content/plugins/kingcomposer/assets/css/icons.css?ver=2.9.6' media='all' />
<link href="{{asset('home/css/style.css')}}" rel="stylesheet">


<!-- End Google Analytics snippet added by Site Kit -->
<link rel="https://api.w.org/" href="https://eforma.fr/wp-json/" /><link rel="alternate" type="application/json" href="https://eforma.fr/wp-json/wp/v2/pages/204" /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://eforma.fr/xmlrpc.php?rsd" />
<meta name="generator" content="WordPress 6.3" />
<link rel='shortlink' href='https://eforma.fr/?p=204' />
<link rel="alternate" type="application/json+oembed" href="https://eforma.fr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Feforma.fr%2Fformation-analyse-financiere%2F" />
<link rel="alternate" type="text/xml+oembed" href="https://eforma.fr/wp-json/oembed/1.0/embed?url=https%3A%2F%2Feforma.fr%2Fformation-analyse-financiere%2F&#038;format=xml" />
<meta name="generator" content="Site Kit by Google 1.104.0" /><!-- Generated by Jetpack Social -->
<meta property="og:title" content="Langues étrangères">
<meta property="og:url" content="https://eforma.fr/formation-analyse-financiere/">
<meta property="og:description" content="Visit the post for more.">
<!-- / Jetpack Social -->
<script type="text/javascript">var kc_script_data={ajax_url:"https://eforma.fr/wp-admin/admin-ajax.php"}</script><link rel="icon" href="https://eforma.fr/wp-content/uploads/2022/08/cropped-cropped-Eforma-Fav-32x32.png" sizes="32x32" />
<link rel="icon" href="https://eforma.fr/wp-content/uploads/2022/08/cropped-cropped-Eforma-Fav-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon" href="https://eforma.fr/wp-content/uploads/2022/08/cropped-cropped-Eforma-Fav-180x180.png" />
<meta name="msapplication-TileImage" content="https://eforma.fr/wp-content/uploads/2022/08/cropped-cropped-Eforma-Fav-270x270.png" />
		<style id="wp-custom-css">
			.imagefix .list-post-type .list-item{
	margin:0px;
	padding:0px;
}
.archive #sidebar{
	display:none;
}
.archive #main{
	padding-top:70px;
}
.single-guide #sidebar{
	display:none;
}
.single-guide #main{
	padding-top:70px;
}
.single .imagesingle img {
    width: 100%;
    height: 400px;
    object-fit: fill;
}
.imagefix .list-post-type .list-item figure{
	margin-bottom:10px;
}
.imagefix .list-post-type .text{
	margin-bottom:10px;
}
.imagefix .kc-entry_meta{
	margin-bottom:0px;
}
.catsidebar ul{
	padding:0px;
}
.catsidebar li{
	    list-style: none;
    display: inline-block;
    background: #fdfbfb;
    margin-bottom: 10px;
    padding: 5px 8px;
    border-radius: 14px;
    font-size: 14px;
    box-shadow: 0px 0px 5px #0000001a;
}
.catsidebar li a {
    color: #121C31;
    font-size: 14px;
}
.dembtns{
  transition-duration: .3s;
    transition-property: transform;
   transition-duration: .3s !important;
    transition-property: transform !important;
    -webkit-transition: all .3s !important;
    -o-transition: all .3s !important;
    transition: all .3s !important;
}
.dembtns:hover{
transform: scale(1.1) !important;
}
.imageclass{
	text-align:center !important;
}
.imageclass img{
	width:70%;
}
.single-post{
	background:#f5f5f5;
}
.mainsingle{
	padding:50px 0px;
}
.innercontnets{
	background:#fff;
	padding: 20px;
	border-radius:10px;
}
.smaebtn{
	border-radius: 50px 50px 50px 50px;
    padding: 17px 30px 17px 30px;
    background: #000;
    display: block;
    text-align: center;
    margin: 13px 10px;
    color: #fff;
	    font-weight: bold;
}
.smaebtn:hover{
	background:#f0f0f0;
	color:#000;
}
.blogposts .post-item-left{
	width:100% !important;
}
.blogposts .post-item-right{
	display:none;
}
.blogposts .kc-list-item-2{
	margin-bottom:0px;
	border: none;
}
.blogposts .kc-list-item-2 .post-title-alt a{
	color: #54595f;
    text-decoration: underline;
    font-size: 18px;
    line-height: 25px;
    text-transform: initial;
}
.blogposts .kc-list-item-2 .post-title-alt{
	margin-bottom:0px;
}
.blogposts .kc-list-item-2 .post-meta{
	margin:0px;
	border:none;
}
.blogposts .kc-post-2-button{
	background: none;
    color: #000;
    float: right;
    border: 1px solid #ffc766;
    font-weight: 600;
    font-size: 16px;
    border-radius: 25px;
    padding: 15px 50px;
}
.blogposts .kc-post-2-button:hover{
	 border: 1px solid #ffeccc;
	background:none;
	color:#000;
}
.kc_button{ 
   transition-duration: .3s;
    transition-property: transform;
    -webkit-transition: all .3s;
    -o-transition: all .3s;
    transition: all .3s;
}

.kc_button:hover{
transform: scale(1.1);
}
#main{
	margin-top:0px;
	margin-bottom:70px;
}
.image_details img{
	    height: 150px;
}
.linksstyle a{
	color:#54595f;
	text-decoration:underline;
}
#header{
	background:none !important;
}
header{
	background:#f5f5f5;
	padding:15px 0px;
	border-bottom:1px solid #d8d8d8;
}
.batitle{
	    background: #000;
    padding: 20px 10px;
	margin:0px !important;
}
.dembtns{
	    border: 3px solid #e38219 !important;
    border-radius: 1px !important;
	    padding: 0px 10px !important;
}
.dembtns:hover{
	background:#e38219 !important;
}

.bottommenu{
	    background: #f0f0f0 !important;
    border-radius: 40px !important;
    padding: 11px !important;
    width: 100%;
    position: absolute !important;
    bottom: 10px !important;
    z-index: 999 !important;
    left: 0px !important;
    width: 85% !important;
    margin: auto !important;
    right: 0px !important;
    padding: 20px 100px !important;
	padding-bottom:10px !important;
}
.sidebarsocial a{
	background:none;
}
.addborder{
	    position: relative;
    padding-bottom: 15px;
}
.addborder:after{
	    content: "";
    position: absolute;
    width: 220px;
    left: 0px;
    bottom: 0px;
    background: #e38219;
    height: 2px;
}
.clientimag img{
	width:150px;
}
#footer {
    background-color: #051421;
    padding: 50px 0px;
	position:relative;
}
#toc_container{
	display:none;
}
#toc_container p.toc_title {
    text-align: left;
}
.innercontnets #toc_container{
	display:block;
	    border: none;
    border-radius: 15px;
}
#maininner .kc-elm {
	padding:0px;
}
.innernav {
	 width: 100%;
	 font-size: 20px;
	 line-height: 60px;
	 background: #f0f0f0;
	 position: relative;
	 z-index: 3;
	box-shadow: 0px 0px 10px 0px rgb(0 0 0 / 50%);
    transition: background 0.3s, border 0.3s, border-radius 0.3s, box-shadow 0.3s;
    z-index: 1;
}
 .sticky {
	 position: fixed;
	 top: 0;
	 left:0px;
	 line-height:50px;
}
.sticky ul{
	margin-bottom:0px;
}
.innernav ul li{
    display: inline-block;
    padding: 0px 20px;
}
.innernav ul{
	padding:0px;
	text-align:center;
}
.innernav ul li a{
color: #000;
    font-size: 14px;
    font-weight: bold;
    text-decoration: underline;
}
footer{
	clear:both;
}
#remvoepadding .kc-elm{
	padding:0px;
}
body{
	    font-family: Jost;
}
.hoverblocs{
	box-shadow:0px 0px 10px 4px rgb(147 144 140 / 32%);
}
.hoverblocs:hover{
	    background: #F0F0F066 !important;
	}

#mega-menu-wrap-main-menu #mega-menu-main-menu li.mega-menu-item a.mega-menu-link:before{
	    font-family: 'FontAwesome';
    position: absolute;
    left: -30px;
    color: #e38219;

}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-megamenu > ul.mega-sub-menu{
    position: fixed;
    width: 100%;
    left: 0;
    right: 0px;
    background: white;
    margin: auto;
    padding: 0px 230px;
    margin-top: 15px;
    padding-bottom: 100px;
    z-index: 999;
    box-shadow: 0px 10px 25px 0px rgb(0 0 0 / 10%);
    padding-top: 20px;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu a.mega-menu-link {
    font-size: 17px !important;
    font-weight: 500 !important;
    text-transform: inherit !important;
    font-family: Jost !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu li.mega-menu-megamenu > ul.mega-sub-menu > li.mega-menu-row .mega-menu-column > ul.mega-sub-menu > li.mega-menu-item {
    padding: 1px;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item > a.mega-menu-link{
	font-size:17px !important;
	font-weight:500 !important;
	    font-family: Jost !important;
	color:#000000;
}
#mega-menu-wrap-main-menu{
	background:none;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item.mega-toggle-on > a.mega-menu-link{
	background:none !important;
	color:#E38219 !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item > a.mega-menu-link:hover{
		background:none !important;
	color:#E38219 !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item.mega-current-menu-item > a.mega-menu-link, #mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item.mega-current-menu-ancestor > a.mega-menu-link, #mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item.mega-current-page-ancestor > a.mega-menu-link{
		background:none !important;
	color:#E38219 !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-item {
    margin: 0 12px 0 0;
}
header .container{
	width:1170px;
}
.borerleft{
	    border-left: 6px solid #e38219;
    padding-left: 25px;
    font-size: 45px !important;
    margin-bottom: 20px;
}
#dispalymenus .mega-current-menu-parent{
	display:none !important;
}
#dispalymenus #mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-megamenu > ul.mega-sub-menu{
   position: relative;
    width: 100%;
    left: 0;
    right: 0px;
    background: none;
    margin: auto;
    padding: 0px 20px;
    margin-top: 0px;
    z-index: 999;
    box-shadow: none;
    height: 520px !important;
    display: block !important;
    opacity: 1 !important;
    z-index: 999;
    transform: translate(0, 0) !important;
    visibility: visible !important;
}
#dispalymenus .mega-menu-item-has-children{
	visibility:hidden !important;
}
#dispalymenus .mega-menu-flyout{
	visibility:hidden !important;
}
#dispalymenus{
	box-shadow:0px 10px 25px 0px rgb(0 0 0 / 10%);
}
#dispalymenus .bottommenu{
padding: 20px 50px !important;
    margin-top: 30px !important;
position: inherit !important;
    bottom: 0px !important;
	width:100% !important;
}

.formstyle input{
	    color: #7a7a7a;
    border: 1px solid #818a91;
    width: 100%;
    padding: 10px;
    margin: 5px 0px;
}
.formstyle .wpcf7-checkbox input{
	display: inline-block;
    width: auto;
}
.formstyle .wpcf7-checkbox input span{
	display:inline-block;
}
.formstyle .wpcf7-checkbox .wpcf7-list-item{
	display:block;
}
.formstyle .wpcf7-submit{
	    background: #e38219;
    color: #fff;
    border: none;
    font-weight: bold;
}
.formstyle textarea{
	  color: #7a7a7a;
    border: 1px solid #818a91;
    width: 100%;
    padding: 10px;
	margin-top:5px;
	height:150px;
}
.setmenufoo ul{
	padding:0px;
}
.setmenufoo ul li{
	list-style:none;
	    line-height: 30px;
}
.setmenufoo a{
	    color: #FFFFFFA6;
    fill: #FFFFFFA6;
    padding-left: 0px;
    padding-right: 0px;
    padding-top: 5px;
    padding-bottom: 5px;
}
.removpeadd .box-right{
	padding-left:10px;
}
#footer{
	padding-bottom:10px;
}
.copyrights{
	color: #a9adb2;
    border-top: 1px solid #1b2b39;
    text-align: center;
    font-size: 12px;
    margin-top: 30px;
    padding-top: 8px;
}
.comclaspress{
	border-left:5px solid #fff;
	border-right:5px solid #fff;
}
.comclaspress img{
	height: 68px;
    margin: auto;
    text-align: center;
    display: block;
}
.newforms input{
	    color: #666;
    padding: 10px;
    height: auto;
    border-width: 1px;
    border-style: solid;
    border-color: #eaeaea;
    border-radius: 2px;
    background: #fafafa;
	width:100%;
}
.newforms textarea{
	    color: #666;
    padding: 10px;
    border-width: 1px;
    border-style: solid;
    border-color: #eaeaea;
    border-radius: 2px;
    background: #fafafa;
		width:100%;
}
.newforms .wpcf7-submit{
	    background: #0170B9;
    color: #fff;
    width: auto;
    padding: 10px 40px;
}

#mega-menu-wrap-main-menu #mega-menu-main-menu > li.dembtns > a.mega-menu-link:hover{
	color:#fff !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu .btsyule a{
	background:#E38219 !important;
	color:#fff !important;
	border-radius:30px !important;
	padding:10px !important;
    text-align: center !important;

}
.container_time{
	width:1170px;
	margin:auto;
}
.inrerblosk{
	background:#fafafa;
	padding: 10px 20px;
}
.inrerblosk h2 a{
	color: #54595f;
    font-size: 20px;
    text-decoration: underline;
}
.inrerblosk .readmores{
	    display: block;
    float: right;
    border: 1px solid #ffc766;
    color: #000;
    padding: 9px 43px;
    border-radius: 28px;
    margin: 31px 0px;
}
.postitmes{
	padding-bottom:50px;
}
.single-post #sidebar{
	display:none;
}
.foocosial a{
	padding: 5px !important;
    background: #3c4650 !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.seconditems > ul.mega-sub-menu{
padding-bottom:20px !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu a.mega-menu-link:hover{
color:#000 !important;
}
#mega-menu-wrap-main-menu #mega-menu-main-menu a.mega-menu-link:hover::before{
color:#000 !important
}
.blogmains{
	padding:0px 50px;
}

@media(max-width:768px){
#mega-menu-wrap-main-menu #mega-menu-main-menu > li.mega-menu-megamenu > ul.mega-sub-menu{
    position: inherit !important;
    padding: 10px 45px;
}
	#mega-menu-wrap-main-menu .mega-menu-toggle{
		background:#f5f5f5;
		   right: -15px;
    position: relative;
	}
	#mega-menu-wrap-main-menu .mega-menu-toggle + #mega-menu-main-menu{
		background:#f5f5f5;
		 
	}
	.bottommenu{
		    position: inherit !important;
    padding: 0px !important;
    width: auto !important;
    background: none !important;
	}
	.clientimag img {
    margin: auto;
    display: block;
}
	h2{
		font-size:28px !important;
	}
	header .container {
    width: 100%;
		    padding: 0px 34px 0px 8px;
	}
	#mega-menu-wrap-main-menu .mega-menu-toggle.mega-menu-open + #mega-menu-main-menu {
    right: -15px;
}
	.sticky {
    position: relative;
	}
}		</style>
		<script type="text/javascript"></script><style type="text/css" id="kc-css-general">.kc-off-notice{display: inline-block !important;}.kc-container{max-width:1170px;}</style><style type="text/css" id="kc-css-render">@media only screen and (min-width:1000px) and (max-width:5000px){body.kc-css-system .kc-css-827020{width:100%;}body.kc-css-system .kc-css-341268{width:65%;}body.kc-css-system .kc-css-227485{width:100%;}body.kc-css-system .kc-css-395457{width:48.58%;}body.kc-css-system .kc-css-883750{width:100%;}body.kc-css-system .kc-css-709407{width:51.41%;}body.kc-css-system .kc-css-32364{width:100%;}body.kc-css-system .kc-css-740118{width:100%;}body.kc-css-system .kc-css-242658{width:25%;}body.kc-css-system .kc-css-406933{width:25%;}body.kc-css-system .kc-css-759486{width:25%;}body.kc-css-system .kc-css-217088{width:25%;}body.kc-css-system .kc-css-866296{width:25%;}body.kc-css-system .kc-css-567431{width:25%;}body.kc-css-system .kc-css-855222{width:25%;}body.kc-css-system .kc-css-467637{width:25%;}body.kc-css-system .kc-css-132337{width:100%;}body.kc-css-system .kc-css-564028{width:100%;}body.kc-css-system .kc-css-402226{width:100%;}body.kc-css-system .kc-css-532282{width:48%;}body.kc-css-system .kc-css-336062{width:100%;}body.kc-css-system .kc-css-442074{width:4%;}body.kc-css-system .kc-css-158267{width:48%;}body.kc-css-system .kc-css-675825{width:100%;}body.kc-css-system .kc-css-452370{width:100%;}body.kc-css-system .kc-css-842302{width:100%;}body.kc-css-system .kc-css-344971{width:35%;}}body.kc-css-system .kc-css-865958{background:linear-gradient(rgba(0, 0, 0, 0.43), rgba(0, 0, 0, 0.43)), transparent url(https://eforma.fr/wp-admin/admin-ajax.php?action=kc_get_thumbn&type=filter_url&id=%2Fwp-content%2Fuploads%2F2022%2F08%2Fbackground-2-2.jpg) 0% 0%/cover repeat scroll;padding-top:150px;padding-bottom:150px;}body.kc-css-system .kc-css-805293.kc_title,body.kc-css-system .kc-css-805293 .kc_title,body.kc-css-system .kc-css-805293 .kc_title a.kc_title_link{color:#ffffff;font-weight:800;text-align:center;}body.kc-css-system .kc-css-793336.kc_title,body.kc-css-system .kc-css-793336 .kc_title,body.kc-css-system .kc-css-793336 .kc_title a.kc_title_link{color:#e38219;font-weight:800;text-align:center;}body.kc-css-system .kc-css-448362{padding-top:90px;padding-bottom:90px;}body.kc-css-system .kc-css-809826.kc_title,body.kc-css-system .kc-css-809826 .kc_title,body.kc-css-system .kc-css-809826 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:600;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-198796 .divider_inner{border-color:#e38219;border-style:solid;width:50%;border-width:3px;}body.kc-css-system .kc-css-198796{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-736794 .content-title{color:#54595f;font-size:20px;font-weight:400;text-transform:capitalize;text-align:left;margin-bottom:5px;padding-left:0px;}body.kc-css-system .kc-css-736794 .content-position{text-transform:capitalize;padding-left:10px;}body.kc-css-system .kc-css-736794 .content-icon i{color:#e38219;font-size:20px;padding-left:10px;}body.kc-css-system .kc-css-736794{margin-top:10px;}body.kc-css-system .kc-css-427123 .content-title{color:#54595f;font-size:20px;font-weight:400;text-transform:capitalize;text-align:left;margin-left:0px;padding-left:0px;}body.kc-css-system .kc-css-427123 .content-position{font-weight:400;text-transform:capitalize;padding-left:10px;}body.kc-css-system .kc-css-427123 .content-icon i{color:#e38219;font-size:20px;padding-left:10px;}body.kc-css-system .kc-css-689835 .content-title{color:#54595f;font-size:20px;font-weight:400;text-transform:capitalize;text-align:left;margin-left:0px;padding-left:0px;}body.kc-css-system .kc-css-689835 .content-position{font-weight:400;text-transform:capitalize;padding-left:10px;}body.kc-css-system .kc-css-689835 .content-icon i{color:#e38219;font-size:20px;padding-left:10px;}body.kc-css-system .kc-css-824885 .kc_button{color:#ffffff;background-color:#e38219;font-size:16px;font-weight:600;padding-right:30px;padding-left:30px;}body.kc-css-system .kc-css-824885{text-align:left;}body.kc-css-system .kc-css-824885 .kc_button i{padding-left:15px;}body.kc-css-system .kc-css-824885 .kc_button:hover{font-size:18px;color:#000000;background-color:#f0f0f0;}.kc-css-628700 .kc_column{padding-left:20px;padding-right:20px;}.kc-css-628700>.kc-wrap-columns{margin-left:-20px;margin-right:-20px;width:calc(100% + 40px);}body.kc-css-system .kc-css-244953{padding-top:30px;}body.kc-css-system .kc-css-520030.kc_title,body.kc-css-system .kc-css-520030 .kc_title,body.kc-css-system .kc-css-520030 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:600;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-238272 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-238272{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-728851{margin-top:20px;}body.kc-css-system .kc-css-395457{background:transparent url(https://eforma.fr/wp-content/uploads/2022/08/cbg-1024x681.jpg) top left/cover no-repeat scroll;margin-left:2%;width:48%;}body.kc-css-system .kc-css-883750{padding:10px 10px 10px 10px;}body.kc-css-system .kc-css-32138.kc_title,body.kc-css-system .kc-css-32138 .kc_title,body.kc-css-system .kc-css-32138 .kc_title a.kc_title_link{color:#e38219;font-size:30px;font-weight:700;line-height:1.1em;text-align:center;margin-top:20px;}body.kc-css-system .kc-css-892514 ,body.kc-css-system .kc-css-892514 p{color:#ffffff;font-size:18px;line-height:24px;}body.kc-css-system .kc-css-892514{padding-top:20px;padding-bottom:20px;}body.kc-css-system .kc-css-892514 p{margin-bottom:10px;}body.kc-css-system .kc-css-709407{background:transparent url(https://eforma.fr/wp-content/uploads/2022/08/cbg.jpg) 0% 0%/cover repeat local;margin-left:2%;width:48%;}.kc-css-389403 >.kc_column_inner,.kc-css-389403 >div>.kc_column_inner{padding-left:10px;padding-right:10px;}.kc-css-389403>.kc-wrap-columns{margin-left:-10px;margin-right:-10px;width:calc(100% + 20px);}body.kc-css-system .kc-css-965616.kc_title,body.kc-css-system .kc-css-965616 .kc_title,body.kc-css-system .kc-css-965616 .kc_title a.kc_title_link{color:#e38219;font-size:30px;font-weight:700;line-height:1.1em;text-align:center;margin-top:20px;}body.kc-css-system .kc-css-299824 ,body.kc-css-system .kc-css-299824 p{color:#ffffff;font-size:18px;line-height:24px;text-align:center;}body.kc-css-system .kc-css-299824{padding-top:20px;padding-bottom:20px;}body.kc-css-system .kc-css-299824 p{margin-bottom:10px;}body.kc-css-system .kc-css-531809{padding-top:30px;}body.kc-css-system .kc-css-672162.kc_title,body.kc-css-system .kc-css-672162 .kc_title,body.kc-css-system .kc-css-672162 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:500;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-518222 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-518222{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-930470{padding-top:50px;padding-bottom:30px;}body.kc-css-system .kc-css-394713{padding-top:30px;}body.kc-css-system .kc-css-813827.kc_title,body.kc-css-system .kc-css-813827 .kc_title,body.kc-css-system .kc-css-813827 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:500;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-240967 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-240967{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-743664 ,body.kc-css-system .kc-css-743664 p{color:#000000;font-size:17px;font-weight:400;}body.kc-css-system .kc-css-743664{padding-top:10px;}body.kc-css-system .kc-css-182858{padding-top:30px;}body.kc-css-system .kc-css-735639.kc_title,body.kc-css-system .kc-css-735639 .kc_title,body.kc-css-system .kc-css-735639 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:500;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-496859 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-496859{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-25868 ,body.kc-css-system .kc-css-25868 p{color:#000000;font-size:17px;font-weight:400;}body.kc-css-system .kc-css-25868{padding-top:10px;}body.kc-css-system .kc-css-100074{padding-top:30px;}body.kc-css-system .kc-css-79827.kc_title,body.kc-css-system .kc-css-79827 .kc_title,body.kc-css-system .kc-css-79827 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:500;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-580641 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-580641{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-31519 ,body.kc-css-system .kc-css-31519 p{color:#000000;font-size:17px;font-weight:400;}body.kc-css-system .kc-css-31519{padding-top:10px;}body.kc-css-system .kc-css-532282{background:#f0f0f0;margin-left:0px;}body.kc-css-system .kc-css-336062{padding:10px 10px 10px 10px;}body.kc-css-system .kc-css-831723 i{color:#e38219;font-size:42px;padding-top:20px;}body.kc-css-system .kc-css-831723{text-align:center;}body.kc-css-system .kc-css-699924.kc_title,body.kc-css-system .kc-css-699924 .kc_title,body.kc-css-system .kc-css-699924 .kc_title a.kc_title_link{color:#000000;font-size:20px;font-weight:700;line-height:1.1em;text-align:center;margin-top:20px;}body.kc-css-system .kc-css-620675 ,body.kc-css-system .kc-css-620675 p{color:#000000;font-size:17px;font-weight:400;text-align:center;}body.kc-css-system .kc-css-620675{padding-top:10px;}body.kc-css-system .kc-css-158267{background:#f0f0f0;}body.kc-css-system .kc-css-675825{padding-top:10px;}body.kc-css-system .kc-css-804322 i{color:#e38219;font-size:42px;padding-top:20px;}body.kc-css-system .kc-css-804322{text-align:center;}body.kc-css-system .kc-css-814219.kc_title,body.kc-css-system .kc-css-814219 .kc_title,body.kc-css-system .kc-css-814219 .kc_title a.kc_title_link{color:#000000;font-size:20px;font-weight:700;line-height:1.1em;text-align:center;margin-top:20px;}body.kc-css-system .kc-css-782207 ,body.kc-css-system .kc-css-782207 p{color:#000000;font-size:17px;font-weight:400;text-align:center;}body.kc-css-system .kc-css-782207{padding-top:10px;}body.kc-css-system .kc-css-589127{padding-top:30px;}body.kc-css-system .kc-css-694726.kc_title,body.kc-css-system .kc-css-694726 .kc_title,body.kc-css-system .kc-css-694726 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:500;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-589650 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-589650{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-320718.kc_title,body.kc-css-system .kc-css-320718 .kc_title,body.kc-css-system .kc-css-320718 .kc_title a.kc_title_link{color:#7a7a7a;font-size:23px;font-weight:500;line-height:1.1em;text-align:left;margin-top:10px;}body.kc-css-system .kc-css-817831 ,body.kc-css-system .kc-css-817831 p{color:#000000;font-size:17px;font-weight:400;}body.kc-css-system .kc-css-817831{padding-top:10px;}body.kc-css-system .kc-css-46146 .kc_button{color:#ffffff;background-color:#e38219;font-size:16px;font-weight:600;padding-right:30px;padding-left:30px;}body.kc-css-system .kc-css-46146{text-align:left;}body.kc-css-system .kc-css-46146 .kc_button:hover{font-size:18px;}body.kc-css-system .kc-css-555447{padding-top:30px;}body.kc-css-system .kc-css-417845.kc_title,body.kc-css-system .kc-css-417845 .kc_title,body.kc-css-system .kc-css-417845 .kc_title a.kc_title_link{color:#000000;font-size:30px;font-weight:500;line-height:1.1em;text-align:left;margin-top:20px;}body.kc-css-system .kc-css-837553 .divider_inner{border-color:#e38219;border-style:solid;width:30%;border-width:3px;}body.kc-css-system .kc-css-837553{text-align:left;margin-top:10px;margin-bottom:0px;}body.kc-css-system .kc-css-827927 ,body.kc-css-system .kc-css-827927 p{color:#000000;font-size:17px;font-weight:400;}body.kc-css-system .kc-css-827927{padding-top:10px;}body.kc-css-system .kc-css-344971{border-radius:5px 5px 5px 5px;}@media only screen and (max-width:767px){body.kc-css-system .kc-css-395457{width:100%;}body.kc-css-system .kc-css-709407{width:100%;}body.kc-css-system .kc-css-532282{width:100%;}body.kc-css-system .kc-css-442074{width:100px;}body.kc-css-system .kc-css-158267{width:100px;}}@media only screen and (max-width:479px){body.kc-css-system .kc-css-448362{padding-top:40px;padding-bottom:40px;}body.kc-css-system .kc-css-809826.kc_title,body.kc-css-system .kc-css-809826 .kc_title,body.kc-css-system .kc-css-809826 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-520030.kc_title,body.kc-css-system .kc-css-520030 .kc_title,body.kc-css-system .kc-css-520030 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-395457{margin-bottom:20px;width:100%;}body.kc-css-system .kc-css-709407{width:100%;}body.kc-css-system .kc-css-672162.kc_title,body.kc-css-system .kc-css-672162 .kc_title,body.kc-css-system .kc-css-672162 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-813827.kc_title,body.kc-css-system .kc-css-813827 .kc_title,body.kc-css-system .kc-css-813827 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-735639.kc_title,body.kc-css-system .kc-css-735639 .kc_title,body.kc-css-system .kc-css-735639 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-79827.kc_title,body.kc-css-system .kc-css-79827 .kc_title,body.kc-css-system .kc-css-79827 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-532282{margin-bottom:20px;width:100%;}body.kc-css-system .kc-css-442074{width:100%;}body.kc-css-system .kc-css-158267{width:100%;}body.kc-css-system .kc-css-694726.kc_title,body.kc-css-system .kc-css-694726 .kc_title,body.kc-css-system .kc-css-694726 .kc_title a.kc_title_link{font-size:25px;}body.kc-css-system .kc-css-417845.kc_title,body.kc-css-system .kc-css-417845 .kc_title,body.kc-css-system .kc-css-417845 .kc_title a.kc_title_link{font-size:25px;}}</style><style type="text/css">/** Mega Menu CSS: fs **/</style>
	<!-- Google tag (gtag.js) --> <script async src=" https://www.googletagmanager.com/gtag/js?id=AW-10849568494 "></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-10849568494'); </script>
		
</head>


<body data-rsssl=1 class="page-template page-template-page-full page-template-page-full-php page page-id-204 kingcomposer kc-css-system mega-menu-main-menu">
    @php
    $categories = App\Models\Category::all();
    @endphp
@include('home.header')
@include('home.topNavbar')




</div></div></div></div></section><section id="maininner" data-kc-fullwidth="content" class="kc-elm kc-css-539334 kc_row"><div class="kc-row-container"><div class="kc-wrap-columns"><div class="kc-elm kc-css-129278 kc_col-sm-12 kc_column kc_col-sm-12"><div class="kc-col-container"><div class="kc-elm kc-css-987742 kc-raw-code"><div class="innernav">
<ul>
<li><a href="#pour-qui">POUR QUI ?</a></li>
<li><a href="#programme">PROGRAMME</a></li>
<li><a href="#objectifs">OBJECTIFS</a></li>
<li><a href="#certificat">CERTIFICAT</a></li>
<li><a href="#points-forts">POINTS FORTS</a></li>
<li><a href="#financement">FINANCEMENT</a></li>

</ul>

</div></div></div></div></div></div></section><section id="mainecontent" class="kc-elm kc-css-653110 kc_row"><div class="kc-row-container  kc-container"><div class="kc-wrap-columns"><div class="kc-elm kc-css-586052 kc_col-sm-12 kc_column kc_col-sm-12"><div class="kc-col-container"><div class="kc-elm kc-css-448362 kc_row kc_row_inner"><div class="kc-elm kc-css-827020 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-809826 kc-title-wrap ">

	<h2 class="kc_title">Apprendre, rafraichir ou renforcer ses connaissances en langue
</h2>
</div>

<div class="kc-elm kc-css-198796 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div class="kc-elm kc-css-736794 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-signal"></i></div><div class="box-right"><div class="content-title">E-learning</div></div>
</div>
<div class="kc-elm kc-css-427123 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-signal"></i></div><div class="box-right"><div class="content-title">Fondamental</div></div>
</div>
<div class="kc-elm kc-css-689835 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-certificate"></i></div><div class="box-right"><div class="content-title">Certifiante</div></div>
</div>

<div class="kc-elm kc-css-824885">
	<a class="kc_button button-box" href="https://eforma.fr/demander-une-demonstration/" target="_self" title="Demonstration" onclick="">
		COMMENCER MAINTENANT <i class="fa-chevron-right"></i>	</a>
</div>
</div></div></div></div></div></div></div></section><section class="kc-elm kc-css-628700 kc_row"><div class="kc-row-container  kc-container"><div class="kc-wrap-columns"><div class="kc-elm kc-css-341268 kc_col-sm-8 kc_column kc_col-sm-8"><div class="kc-col-container"><div id="pour-qui" class="kc-elm kc-css-244953 kc_row kc_row_inner"><div class="kc-elm kc-css-227485 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-520030 kc-title-wrap ">

	<h2 class="kc_title">A qui s'adresse cette formation ?
</h2>
</div>

<div class="kc-elm kc-css-238272 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
</div></div></div><div class="kc-elm kc-css-728851 kc_row kc_row_inner"><div class="kc-elm kc-css-395457 kc_col-sm-6 kc_column_inner kc_col-sm-6"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-997814 kc_row kc_row_inner"><div class="kc-elm kc-css-883750 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-32138 kc-title-wrap ">

	<h2 class="kc_title">Pour qui
</h2>
</div>
<div class="kc-elm kc-css-892514 kc_text_block"><p>Pour tout le monde</p>
</div></div></div></div></div></div><div class="kc-elm kc-css-709407 kc_col-sm-6 kc_column_inner kc_col-sm-6"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-389403 kc_row kc_row_inner"><div class="kc-elm kc-css-32364 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-965616 kc-title-wrap ">

	<h2 class="kc_title">Prérequis
</h2>
</div>
<div class="kc-elm kc-css-299824 kc_text_block"><p>Aucun</p>
</div></div></div></div></div></div></div><div id="programme" class="kc-elm kc-css-531809 kc_row kc_row_inner"><div class="kc-elm kc-css-740118 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-672162 kc-title-wrap ">

	<h2 class="kc_title">Les différentes langues
</h2>
</div>

<div class="kc-elm kc-css-518222 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div id="objectifs" class="kc-elm kc-css-930470 kc_row kc_row_inner"><div class="kc-elm kc-css-242658 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-173853 kc_shortcode kc_single_image">

        <img src="https://eforma.fr/wp-content/uploads/2022/08/apprendre-anglqis-150x150-1.png" class="" alt="" />    </div>
</div></div><div class="kc-elm kc-css-406933 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-623498 kc_shortcode kc_single_image">

        <img src="https://eforma.fr/wp-content/uploads/2022/08/apprendre-espagnol-150x150-1.jpg" class="" alt="" />    </div>
</div></div><div class="kc-elm kc-css-759486 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-855882 kc_shortcode kc_single_image">

        <img src="https://eforma.fr/wp-content/uploads/2022/08/apprendre-allemand-150x150-1.jpg" class="" alt="" />    </div>
</div></div><div class="kc-elm kc-css-217088 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-269208 kc_shortcode kc_single_image">

        <img src="https://eforma.fr/wp-content/uploads/2022/08/apprendre-le-portugais-150x150-1.png" class="" alt="" />    </div>
</div></div></div><div class="kc-elm kc-css-94426 kc_row kc_row_inner"><div class="kc-elm kc-css-866296 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-702970 kc_shortcode kc_single_image">

        <img src="https://eforma.fr/wp-content/uploads/2022/08/drapeau-france-francais-150-x-90-cm-150x150-1.jpg" class="" alt="" />    </div>
</div></div><div class="kc-elm kc-css-567431 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-661320 kc_shortcode kc_single_image">

        <img src="https://eforma.fr/wp-content/uploads/2022/08/apprendre-italien-150x150-1.jpeg" class="" alt="" />    </div>
</div></div><div class="kc-elm kc-css-855222 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"></div></div><div class="kc-elm kc-css-467637 kc_col-sm-3 kc_column_inner kc_col-sm-3"><div class="kc_wrapper kc-col-inner-container"></div></div></div></div></div></div><div class="kc-elm kc-css-394713 kc_row kc_row_inner"><div class="kc-elm kc-css-132337 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-813827 kc-title-wrap ">

	<h2 class="kc_title">Le Programme standard d'une formation en langue
</h2>
</div>

<div class="kc-elm kc-css-240967 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div class="kc-elm kc-css-743664 kc_text_block"><p><strong>Descriptions des modules linguistiques <br /></strong>Chaque module met en valeur différentes compétences linguistiques et de vocabulaire.</p>
<p><strong>Module 1-4 :</strong> ces cours aident à acquérir des bases solides avec le vocabulaire fondamental et les principales structures de langue.</p>
<p>Le vocabulaire et les compétences mises en valeur comprennent :</p>
<ul>
<li>Salutations et présentations</li>
<li>Questions et réponses simples</li>
<li>Shopping</li>
<li>Compétences de compréhension orale</li>
<li>Compétences de lecture et d’écriture de base</li>
</ul>
<p><strong>Module 5-8 : </strong>ces cours permettent aux apprenants de naviguer dans leur environnement en continuant à bâtir sur le vocabulaire fondamental et les principales structures de langue des modules 1 à 4.</p>
<p>Le vocabulaire et les compétences mises en valeur comprennent :</p>
<ul>
<li>Donner et obtenir des instructions</li>
<li>Utiliser les transports</li>
<li>Dire l’heure</li>
<li>Sortir au restaurant</li>
<li>Profiter des interactions sociales de base</li>
<li>Vie professionnelle</li>
<li>Sujets de cours</li>
<li>Arts et culture</li>
<li>Temps passé, présent et futur</li>
</ul>
<p><strong>Module 9-12 </strong>ces cours permettent aux apprenants de communiquer avec le monde qui les entoure en continuant à bâtir sur les notions de base et les compétences de conversation développées dans les modules 1 à 8.</p>
<p><strong>Le vocabulaire et les compétences mises en valeur comprennent :</strong></p>
<ul>
<li>Idées et opinions</li>
<li>Sentiments à propos de la vie de tous les jours</li>
<li>Intérêts</li>
<li>Travail</li>
<li>Événements actuels</li>
<li>Naissance, mariage, décès et inquiétudes liées à la santé et au corps</li>
<li>Termes supplémentaires indiquant la fréquence, la durée et les degrés</li>
</ul>
<p><strong>Module 13-16 :</strong> ces cours offrent aux apprenants l’opportunité d’accroître leur compréhension de la langue en continuant à bâtir sur leurs succès obtenus dans les modules de 1 à 12.</p>
<p>Le vocabulaire et les compétences mises en valeur comprennent :</p>
<ul>
<li>Naviguer dans votre lieu de travail</li>
<li>Se soucier de la santé</li>
<li>Organiser des réparations</li>
<li>Déménager à l’étranger</li>
<li>Conduite</li>
<li>Planification d’aventures</li>
<li>Santé et états mentaux pour eux et les autres</li>
<li>Exprimer ses goûts personnels en termes de préférences matérielles et sensorielles.</li>
</ul>
<p><strong>Module 17-20 : </strong>ces cours permettent aux apprenants de développer leur maîtrise de la langue tout en affinant les compétences de communication essentielles acquises dans les modules 1 à 16.</p>
<p>Le vocabulaire et les compétences mises en valeur comprennent :</p>
<ul>
<li>
<ul>
<li>Situations d’urgence</li>
<li>Divertissements</li>
<li>Secteur administratif d’État</li>
<li>Le marché</li>
<li>Apprendre à connaître un quartier</li>
<li>Famille et traditions</li>
<li>Célébrer votre réussite</li>
<li>Bénévolat</li>
<li>Exprimer ses inquiétudes personnelles, objectifs et accomplissements</li>
</ul>
</li>
</ul>
</div></div></div></div><div id="certificat" class="kc-elm kc-css-182858 kc_row kc_row_inner"><div class="kc-elm kc-css-564028 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-735639 kc-title-wrap ">

	<h2 class="kc_title">Certificats</h2>
</div>

<div class="kc-elm kc-css-496859 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div class="kc-elm kc-css-25868 kc_text_block"><ul>
<li>Évaluation des compétences à certifier via un questionnaire en ligne intégrant des mises en situation avec Pipplet- Bright TOEIC</li>
</ul>
</div></div></div></div><div id="points-forts" class="kc-elm kc-css-100074 kc_row kc_row_inner"><div class="kc-elm kc-css-402226 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-79827 kc-title-wrap ">

	<h2 class="kc_title">Les points forts de la formation
</h2>
</div>

<div class="kc-elm kc-css-580641 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div class="kc-elm kc-css-31519 kc_text_block"><ul>
<li>Formation E-Learning interactive</li>
<li>Entrainement visuels et audios</li>
<li>Multiples jeux-exercices interactifs et stimulants.</li>
<li>Support de cours disponibles imprimables pendant tout le parcours de formation</li>
</ul>
</div></div></div></div><div class="kc-elm kc-css-167746 kc_row kc_row_inner"><div class="kc-elm kc-css-532282 kc_col-sm-6 kc_column_inner kc_col-sm-6 hoverblocs"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-413888 kc_row kc_row_inner"><div class="kc-elm kc-css-336062 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-831723 kc-icon-wrapper">
		<i class="fa-graduation-cap"></i>
	</div>

<div class="kc-elm kc-css-699924 kc-title-wrap ">

	<h2 class="kc_title">Formateurs experts
</h2>
</div>
<div class="kc-elm kc-css-620675 kc_text_block"><p>Nos formateurs sont qualifiés et expérimentés. Ils sont disponibles à tout moment en Chat asynchrone ou par courriel.</p>
</div></div></div></div></div></div><div class="kc-elm kc-css-442074 kc_col-sm-1 kc_column_inner kc_col-sm-1"><div class="kc_wrapper kc-col-inner-container"></div></div><div class="kc-elm kc-css-158267 kc_col-sm-6 kc_column_inner kc_col-sm-6 hoverblocs"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-933344 kc_row kc_row_inner"><div class="kc-elm kc-css-675825 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container"><div class="kc-elm kc-css-804322 kc-icon-wrapper">
		<i class="fa-graduation-cap"></i>
	</div>

<div class="kc-elm kc-css-814219 kc-title-wrap ">

	<h2 class="kc_title">Qualité des formations
</h2>
</div>
<div class="kc-elm kc-css-782207 kc_text_block"><p>Nos formations interactives et attractives plaisent aux apprenants ce qui a pour conséquence de favoriser la complétion du parcours de formation.</p>
</div></div></div></div></div></div></div><div id="financement" class="kc-elm kc-css-589127 kc_row kc_row_inner"><div class="kc-elm kc-css-452370 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-694726 kc-title-wrap ">

	<h2 class="kc_title">Les solutions de financement
</h2>
</div>

<div class="kc-elm kc-css-589650 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>

<div class="kc-elm kc-css-320718 kc-title-wrap ">

	<h3 class="kc_title">OPCO Et Financement De La Formation
</h3>
</div>
<div class="kc-elm kc-css-817831 kc_text_block"><p>Depuis janvier 2019, et la loi « Avenir professionnel », les opérateurs ont connu un élargissement des champs de compétences et ont pour mission d’octroyer des financements.</p>
<p>En cas de questions sur l’éligibilité d’un futur stagiaire à un financement particulier, une équipe qualifiée sera à votre disposition pour vous assister dans vos formalités.</p>
</div>
<div class="kc-elm kc-css-46146">
	<a class="kc_button button-box" href="https://eforma.fr/demander-une-demonstration/" target="_self" title="Demonstration" onclick="">
		COMMENCER MAINTENANT <i class="sl-arrow-right"></i>	</a>
</div>
</div></div></div><div class="kc-elm kc-css-555447 kc_row kc_row_inner"><div class="kc-elm kc-css-842302 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-417845 kc-title-wrap ">

	<h2 class="kc_title">Cette formation est éligible au CPF
</h2>
</div>

<div class="kc-elm kc-css-837553 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div class="kc-elm kc-css-827927 kc_text_block"><p><strong>Cette formation est certifiante et donc éligible au CPF.</strong></p>
<p>Les formations éligibles au Compte formation (CPF) sont essentiellement certifiantes ou qualifiantes.</p>
<p>Il s’agit de formations permettant d’acquérir le socle de connaissances et de compétences et les actions de formation sanctionnées par une certification enregistrée dans le Répertoire national des certifications professionnelles (RNCP) ou permettant d’obtenir tout ou partie identifiée de certification professionnelle, classée dans le RNCP, visant l’acquisition d’un bloc de compétences ou encore d’actions de formation sanctionnées par une certification enregistrée dans le Répertoire spécifique (RS) établi par la Commission de la certification professionnelle de France Compétences.</p>
<p>Cette formation étant adossée plusieurs certifications en langues étrangères, elle permettra à vos apprenants un financement par le mécanisme des fonds mutualisés de la formation professionnelle.</p>
<p><strong>Attention, la certification est nécessaire pour justifier de ce financement,</strong></p>
<p>Ces tests sont des évaluations qui permettent de déterminer le niveau de langues étrangères du niveau A1 à C2 du CECR, vos apprenants ne pourront donc ni échouer ni réussir.</p>
</div></div></div></div></div></div><div id="siderscrooll" class="kc-elm kc-css-344971 kc_col-sm-4 kc_column kc_col-sm-4"><div class="kc-col-container"><div class="kc-elm kc-css-335968 kc-raw-code"><style type="text/css">@media only screen and (min-width: 1000px) and (max-width: 5000px){body.kc-css-system .kc-css-522666{width: 100%;}body.kc-css-system .kc-css-456465{width: 100%;}}body.kc-css-system .kc-css-333371{background: #f0f0f0;padding: 30px 20px 30px 20px;border-radius: 5px 5px 5px 5px;}body.kc-css-system .kc-css-282674.kc_title,body.kc-css-system .kc-css-282674 .kc_title,body.kc-css-system .kc-css-282674 .kc_title a.kc_title_link{color: #000000;font-size: 30px;font-weight: 700;line-height: 1.1em;text-align: center;margin-top: 0px;margin-bottom: 0px;}body.kc-css-system .kc-css-45084 .divider_inner{border-color: #e38219;border-style: solid;width: 38%;border-width: 3px;}body.kc-css-system .kc-css-45084{text-align: center;margin-top: 0px;margin-bottom: 0px;}body.kc-css-system .kc-css-769517{margin-top: 30px;margin-bottom: 20px;}body.kc-css-system .kc-css-456465{background: #f7f7f7;}body.kc-css-system .kc-css-518140.kc_title,body.kc-css-system .kc-css-518140 .kc_title,body.kc-css-system .kc-css-518140 .kc_title a.kc_title_link{color: #ffffff;font-size: 20px;font-weight: 700;line-height: 1.1em;text-align: center;margin-top: 20px;margin-bottom: 20px;}body.kc-css-system .kc-css-820955 .content-title{color: #54595f;font-size: 20px;font-weight: 400;text-transform: capitalize;text-align: center;margin-bottom: 5px;padding-left: 0px;}body.kc-css-system .kc-css-820955 .content-position{text-transform: capitalize;padding-left: 10px;}body.kc-css-system .kc-css-820955 .content-icon i{color: #54595f;font-size: 20px;padding-left: 10px;}body.kc-css-system .kc-css-820955{text-align: center;margin-top: 10px;}body.kc-css-system .kc-css-673744 .content-title{color: #54595f;font-size: 20px;font-weight: 400;text-transform: capitalize;text-align: center;margin-bottom: 5px;padding-left: 0px;}body.kc-css-system .kc-css-673744 .content-position{text-transform: capitalize;padding-left: 10px;}body.kc-css-system .kc-css-673744 .content-icon i{color: #54595f;font-size: 20px;padding-left: 10px;}body.kc-css-system .kc-css-673744{text-align: center;margin-top: 10px;}body.kc-css-system .kc-css-923592 .content-title{color: #54595f;font-size: 20px;font-weight: 400;text-transform: capitalize;text-align: center;margin-bottom: 5px;padding-left: 0px;}body.kc-css-system .kc-css-923592 .content-position{text-transform: capitalize;padding-left: 10px;}body.kc-css-system .kc-css-923592 .content-icon i{color: #54595f;font-size: 20px;padding-left: 10px;}body.kc-css-system .kc-css-923592{text-align: center;margin-top: 10px;}body.kc-css-system .kc-css-164594 .kc_button{color: #ffffff;background-color: #e38219;font-size: 16px;font-weight: 600;padding-right: 30px;padding-left: 30px;margin-bottom: 30px;}body.kc-css-system .kc-css-164594{text-align: center;}body.kc-css-system .kc-css-164594 .kc_button:hover{font-size: 18px;}body.kc-css-system .kc-css-575521 ,body.kc-css-system .kc-css-575521 p{color: #000000;font-size: 17px;font-weight: 500;text-align: center;}body.kc-css-system .kc-css-575521{padding-top: 10px;}body.kc-css-system .kc-css-893396 i{color: #000000;}body.kc-css-system .kc-css-893396 a{text-align: center;}body.kc-css-system .kc-css-893396{text-align: center;}</style><section class="kc-elm kc-css-273333 kc_row"><div class="kc-row-container  kc-container"><div class="kc-wrap-columns"><div id="siderscrooll" class="kc-elm kc-css-935513 kc_col-sm-12 kc_column kc_col-sm-12"><div class="kc-col-container"><div class="kc-elm kc-css-333371 kc_row kc_row_inner"><div class="kc-elm kc-css-522666 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-282674 kc-title-wrap ">

	<h2 class="kc_title">CARACTERIQUES​
</h2>
</div>

<div class="kc-elm kc-css-45084 divider_line">
	<div class="divider_inner divider_line1">
			</div>
</div>
<div id="remvoepadding" class="kc-elm kc-css-769517 kc_row kc_row_inner"><div class="kc-elm kc-css-456465 kc_col-sm-12 kc_column_inner kc_col-sm-12"><div class="kc_wrapper kc-col-inner-container">
<div class="kc-elm kc-css-518140 kc-title-wrap ">

	<h2 class="kc_title batitle">PRIX UNITAIRE POUR UN OF</h2>
</div>
<div class="kc-elm kc-css-820955 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fab-gratipay"></i></div><div class="box-right"><div class="content-title">Formation E-learning</div></div>
</div>
<div class="kc-elm kc-css-673744 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="sl-clock"></i></div><div class="box-right"><div class="content-title">Durée 12h</div></div>
</div>
<div class="kc-elm kc-css-923592 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-euro-sign"></i></div><div class="box-right"><div class="content-title"> Prix sur demande</div></div>
</div>
<div class="kc-elm kc-css-887348" style="height: 20px; clear: both; width:100%;"></div>
<div class="kc-elm kc-css-164594">
	<a class="kc_button button-box" href="https://eforma.fr/demander-une-demonstration/" target="_self" title="" onclick="">
		S&#039;inscrire	</a>
</div>
</div></div></div><div class="kc-elm kc-css-575521 kc_text_block"><p>Partager cette formation</p>
</div><div class="kc-elm kc-css-893396 kc-multi-icons-wrapper sidebarsocial">
			<a href="#" target="_blank" title="Facebook" class="multi-icons-link multi-iconsfab-facebook-f">
			<i class="fab-facebook-f" style="color:#000000;"></i>
		</a>

			<a href="#" target="_blank" title="Twitter" class="multi-icons-link multi-iconsfab-twitter">
			<i class="fab-twitter"></i>
		</a>

			<a href="#" target="_blank" title="" class="multi-icons-link multi-iconsfab-linkedin">
			<i class="fab-linkedin"></i>
		</a>

			<a href="#" target="_blank" title="" class="multi-icons-link multi-iconssl-envolope">
			<i class="sl-envolope"></i>
		</a>

	</div>
</div></div></div></div></div></div></div></section></div></div></div></div></div></section></div><!-- /#post-204 -->
					</main><!-- /#main -->
<footer id="footer">
			<div class="container">
				<style type="text/css">@media only screen and (min-width: 1000px) and (max-width: 5000px){body.kc-css-system .kc-css-184697{width: 25%;}body.kc-css-system .kc-css-18249{width: 25%;}body.kc-css-system .kc-css-108712{width: 25%;}body.kc-css-system .kc-css-183062{width: 25%;}}.kc-css-425365 .kc_column{padding-left: 40px;padding-right: 40px;}.kc-css-425365>.kc-wrap-columns{margin-left: -40px;margin-right: -40px;width: calc(100% + 80px);}body.kc-css-system .kc-css-729830 ,body.kc-css-system .kc-css-729830 p{color: #a9adb2;}body.kc-css-system .kc-css-760493.kc_title,body.kc-css-system .kc-css-760493 .kc_title,body.kc-css-system .kc-css-760493 .kc_title a.kc_title_link{color: #ffffff;font-size: 20px;font-weight: 500;margin-bottom: 10px;}body.kc-css-system .kc-css-713188.kc_title,body.kc-css-system .kc-css-713188 .kc_title,body.kc-css-system .kc-css-713188 .kc_title a.kc_title_link{color: #ffffff;font-size: 20px;font-weight: 500;margin-bottom: 10px;}body.kc-css-system .kc-css-228828.kc_title,body.kc-css-system .kc-css-228828 .kc_title,body.kc-css-system .kc-css-228828 .kc_title a.kc_title_link{color: #ffffff;font-size: 20px;font-weight: 500;margin-bottom: 10px;}body.kc-css-system .kc-css-396336 .content-desc{color: #a9adb2;padding-right: 0px;padding-left: 0px;}body.kc-css-system .kc-css-396336 .content-icon i{color: #e38219;font-size: 20px;width: 25px;}body.kc-css-system .kc-css-396336{padding-right: 0px;padding-left: 5px;}body.kc-css-system .kc-css-308941 .content-desc{color: #a9adb2;padding-right: 0px;padding-left: 0px;}body.kc-css-system .kc-css-308941 .content-icon i{color: #e38219;font-size: 20px;width: 25px;}body.kc-css-system .kc-css-308941{padding-right: 0px;padding-left: 5px;}body.kc-css-system .kc-css-568472 .content-desc{color: #a9adb2;padding-right: 0px;padding-left: 0px;}body.kc-css-system .kc-css-568472 .content-icon i{color: #e38219;font-size: 20px;width: 25px;}body.kc-css-system .kc-css-568472{padding-right: 0px;padding-left: 5px;}body.kc-css-system .kc-css-987123 .content-desc{color: #a9adb2;padding-right: 0px;padding-left: 0px;}body.kc-css-system .kc-css-987123 .content-icon i{color: #e38219;font-size: 20px;width: 25px;}body.kc-css-system .kc-css-987123{padding-right: 0px;padding-left: 5px;}</style><section class="kc-elm kc-css-425365 kc_row"><div class="kc-row-container  kc-container"><div class="kc-wrap-columns"><div class="kc-elm kc-css-184697 kc_col-sm-3 kc_column kc_col-sm-3"><div class="kc-col-container"><div class="kc-elm kc-css-437607 kc_shortcode kc_single_image">

        <img decoding="async" src="https://eforma.fr/wp-content/uploads/2022/08/eforma.png" class="" alt="" />    </div>
<div class="kc-elm kc-css-729830 kc_text_block"><p>EFORMA est une marque de Eforma Technologies SASU.<br />Eforma propose une solution complète comprenant un CRM/ LMS ainsi que du contenu sur étagères pour  faciliter la vie des professionnels de la formation et de leurs apprenants.</p>
</div><div class="kc-elm kc-css-368752 kc-multi-icons-wrapper foocosial">
			<a href="https://www.facebook.com/eforma.fr" target="_self" title="" class="multi-icons-link multi-iconsfab-facebook-f">
			<i class="fab-facebook-f"></i>
		</a>

			<a href="#" target="_blank" title="Twitter" class="multi-icons-link multi-iconsfab-twitter">
			<i class="fab-twitter"></i>
		</a>

			<a href="https://www.instagram.com/eforma.fr/" target="_self" title="" class="multi-icons-link multi-iconsfab-instagram">
			<i class="fab-instagram"></i>
		</a>

			<a href="https://www.linkedin.com/company/eforma-fr/" target="_self" title="" class="multi-icons-link multi-iconsfab-linkedin">
			<i class="fab-linkedin"></i>
		</a>

	</div>
</div></div><div class="kc-elm kc-css-18249 kc_col-sm-3 kc_column kc_col-sm-3 setmenufoo"><div class="kc-col-container">
<div class="kc-elm kc-css-760493 kc-title-wrap ">

	<h2 class="kc_title">Legales</h2>
</div>
<div class="kc-elm kc-css-458586 kc-raw-code"><div class="menu-legales-menu-container"><ul id="menu-legales-menu" class="myclass"><li id="menu-item-742" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-742"><a href="https://eforma.fr/conditions-generales/">Conditions générales</a></li>
<li id="menu-item-741" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-741"><a href="https://eforma.fr/confidentialite/">Politique de confidentialité</a></li>
<li id="menu-item-740" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-740"><a href="https://eforma.fr/contrat-dutilisation/">Contrat d’utilisation</a></li>
<li id="menu-item-739" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-739"><a href="https://eforma.fr/conditions-pour-les-formateurs/">Conditions pour les formateurs</a></li>
<li id="menu-item-736" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-736"><a href="https://eforma.fr/condition-utilisation-of/">Conditions d’utilisation pour les Organismes de Formation</a></li>
<li id="menu-item-738" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-738"><a href="https://eforma.fr/conditions-pour-les-affilies/">Conditions pour les affiliés</a></li>
<li id="menu-item-737" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-737"><a href="https://eforma.fr/utilisation-des-apis/">Utilisation des APIs</a></li>
</ul></div></div></div></div><div class="kc-elm kc-css-108712 kc_col-sm-3 kc_column kc_col-sm-3 setmenufoo"><div class="kc-col-container">
<div class="kc-elm kc-css-713188 kc-title-wrap ">

	<h2 class="kc_title">Liens Rapides
</h2>
</div>
<div class="kc-elm kc-css-822019 kc-raw-code"><div class="menu-liens-menus-container"><ul id="menu-liens-menus" class="myclass"><li id="menu-item-786" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home menu-item-786"><a href="https://eforma.fr/">Formation E-Learning</a></li>
<li id="menu-item-787" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-787"><a href="https://eforma.fr/logiciel-de-gestion-pour-organisme-de-formation/">CRM &#038; LMS</a></li>
<li id="menu-item-788" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-788"><a href="https://eforma.fr/rejoindre-eforma/">Carrière</a></li>
<li id="menu-item-951" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-951"><a href="https://eforma.fr/blog/">Informations</a></li>
<li id="menu-item-1219" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1219"><a href="https://formateur.eforma.fr">Devenir formateur</a></li>
</ul></div></div></div></div><div class="kc-elm kc-css-183062 kc_col-sm-3 kc_column kc_col-sm-3 removpeadd"><div class="kc-col-container">
<div class="kc-elm kc-css-228828 kc-title-wrap ">

	<h2 class="kc_title">Adresse</h2>
</div>
<div class="kc-elm kc-css-396336 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-map-marker-alt"></i></div><div class="box-right"><div class="content-desc">25 rue de Ponthieu, 75008 Paris, France</div></div>
</div>
<div class="kc-elm kc-css-308941 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-map-marker-alt"></i></div><div class="box-right"><div class="content-desc">29 rue du Rouet, 
13006 Marseille, France</div></div>
</div>
<div class="kc-elm kc-css-568472 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="fa-phone"></i></div><div class="box-right"><div class="content-desc">+33175439969</div></div>
</div>
<div class="kc-elm kc-css-987123 kc-feature-boxes kc-fb-layout-3">

	<div class="content-icon"><i class="sl-envolope"></i></div><div class="box-right"><div class="content-desc">info@eforma.fr</div></div>
</div>
</div></div></div></div></section>				<div class="row">
					
									</div><!-- /.row -->
			</div><!-- /.container -->
			<div class="copyrights">
				<p>© 2021 Eforma.fr SAS</p>
			</div>
		</footer><!-- /#footer -->
	</div><!-- /#wrapper -->
	<script src='https://eforma.fr/wp-content/plugins/contact-form-7/includes/swv/js/index.js?ver=5.8' id='swv-js'></script>
<script id='contact-form-7-js-extra'>
	<!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{{asset('home/lib/easing/easing.min.js')}}"></script>
    <script src="{{asset('home/lib/owlcarousel/owl.carousel.min.js')}}"></script>

    <!-- Contact Javascript File -->
    <script src="{{asset('home/mail/jqBootstrapValidation.min.js')}}"></script>
    <script src="{{asset('home/mail/contact.js')}}"></script>

    <!-- Template Javascript -->
    <script src="{{asset('home/js/main.js')}}"></script>
var wpcf7 = {"api":{"root":"https:\/\/eforma.fr\/wp-json\/","namespace":"contact-form-7\/v1"},"cached":"1"};
</script>
<script src='https://eforma.fr/wp-content/plugins/contact-form-7/includes/js/index.js?ver=5.8' id='contact-form-7-js'></script>
<script src='https://eforma.fr/wp-content/plugins/table-of-contents-plus/front.min.js?ver=2302' id='toc-front-js'></script>
<script src='https://eforma.fr/wp-content/themes/eforma/assets/js/main.bundle.js?ver=3.0.3' id='mainjs-js'></script>
<script src='https://eforma.fr/wp-content/plugins/mystickysidebar/js/detectmobilebrowser.js?ver=1.2.3' id='detectmobilebrowser-js'></script>
<script id='mystickysidebar-js-extra'>
var mystickyside_name = {"mystickyside_string":"#siderscrooll","mystickyside_content_string":"","mystickyside_margin_top_string":"90","mystickyside_margin_bot_string":"0","mystickyside_update_sidebar_height_string":"false","mystickyside_min_width_string":"795","device_desktop":"1","device_mobile":"1"};
</script>
<script src='https://eforma.fr/wp-content/plugins/mystickysidebar/js/theia-sticky-sidebar.js?ver=1.2.3' id='mystickysidebar-js'></script>
<script src='https://eforma.fr/wp-includes/js/hoverIntent.min.js?ver=1.10.2' id='hoverIntent-js'></script>
<script id='megamenu-js-extra'>
var megamenu = {"timeout":"300","interval":"100"};
</script>
<script src='https://eforma.fr/wp-content/plugins/megamenu/js/maxmegamenu.js?ver=3.2.2' id='megamenu-js'></script>
<script src='https://eforma.fr/wp-content/plugins/kingcomposer/assets/frontend/js/kingcomposer.min.js?ver=2.9.6' id='kc-front-scripts-js'></script>

	<script type="text/javascript">
		var yourNavigation = jQuery(".innernav");
			    stickyDiv = "sticky";
			    yourHeader = jQuery('#mainecontent').height();

			jQuery(window).scroll(function() {
			  if( jQuery(this).scrollTop() > yourHeader ) {
			    yourNavigation.addClass(stickyDiv);
			  } else {
			    yourNavigation.removeClass(stickyDiv);
			  }
			});

			document.addEventListener( 'wpcf7mailsent', function( e ) {
			    var url_redirect = '';

			    var inputs = e.detail.inputs;
			    for ( var i = 0; i < inputs.length; i++ ) {

			        if( 'url_redirect' == inputs[i].name ) {//used for misc forms
			            url_redirect = inputs[i].value;//set the redirect value from current submitted form
			        }

			    }

			    //Check for redirect 
			    if( url_redirect ){
			        location = url_redirect;
			    }

			}, false ); 

			


			jQuery(document).ready(function() {
  // Select the sidebar element
  const sidebar = jQuery('.sidebartop');

  // Get the distance of the sidebar from the top of the page
  const sidebarTopOffset = sidebar.offset().top;

  // Add an event listener to the window object for scroll event
  jQuery(window).scroll(function() {
    // Get the current scroll position of the page
    const scrollPos = jQuery(this).scrollTop();

    // Check if the scroll position is greater than or equal to the sidebar's top offset
    if (scrollPos >= sidebarTopOffset) {
      // If it is, add the 'sticky' class to the sidebar element
      sidebar.addClass('stickynew');
    } else {
      // If it isn't, remove the 'sticky' class from the sidebar element
      sidebar.removeClass('stickynew');
    }
  });
});


	</script>

<style type="text/css">
	.sidebartop {
  /* Set the initial position of the sidebar */
  position: relative;
}

.stickynew {
 position: fixed;
    top: 0;
    width: 360px !important;
}
@media(max-width: 768px){
	.stickynew{
		position: inherit;
		width: 100% !important;
	}
}
</style>
</body>
</html>


<!-- Page supported by LiteSpeed Cache 5.5.1 on 2023-08-10 22:45:53 -->